baseURL = "https://paras55blog.netlify.app"
languageCode = "en-us"
title = "Startup Nerd"
summaryLength = 20
paginate = 5
# Google Analytics ID, Uncomment below line to enable
# googleAnalytics = "UA-123-45"

# Enter your disqus Shortname and uncomment below line to enable
# disqusShortname = "yourdiscussshortname"

[params]
favicon = "images/favicon.png"
herotitle = "Catch the latest episode here"
herolink = "https://undraw.co/search"
herolinktext = "Check Now"
contact = "Send me a message and I will get back as soon as possible."

[hero]

[menu]
    
    [[menu.nav]]
        name    = "Blogs"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -2
    [[menu.nav]]
        name    = "Contact"
        pre = "<i class='fas fa-envelope'></i>"
        url     = "contact"
        weight  = -3
